###########################################################
# 1.0 - AGENT GRAPH DEFINITION
# This module defines the multi-agent workflow graph that orchestrates the interactions between the Planner, Retriever
# , Reasoning, and Validator agents. Each agent is implemented as a node in the graph, with specific functions that process the shared state. The graph includes conditional routing logic to ensure that if the Validator detects any hallucinations in the Reasoning Agent's output, it loops back to the Retriever for additional context retrieval. The final compiled graph is exported for execution in the main application.
#############################################################
# For typing the shared state structure across agents
from typing import TypedDict, List
# For defining structured output schemas that Gemini will adhere to, enabling self-auditing in a single pass
from pydantic import BaseModel, Field
# For constructing the multi-agent workflow graph with conditional routing
from langgraph.graph import StateGraph, END
from langchain_google_genai import ChatGoogleGenerativeAI   # For connecting to
# For structuring the prompts sent to
from langchain_core.messages import SystemMessage, HumanMessage
# For chromaDB interactions, abstracted as a service layer
from app.services.vector_store import VectorStoreService
# For accessing configuration variables like API keys
from app.core.config import settings

# 1. DEFINE THE STRUCTURED OUTPUT BLUEPRINT


class JointResponseSchema(BaseModel):
    """Pydantic schema forcing Gemini to reason and self-audit in a single invocation."""
    response: str = Field(
        description="The short, objective response formulated strictly using the context sources."
    )
    is_valid: bool = Field(
        description="True if the response is 100% grounded in the context text. False if any ungrounded assumptions were made."
    )

# 2. DEFINE THE CENTRALIZED AGENT MEMORY STATE


class AgentState(TypedDict):
    query: str           # The raw natural language question from the user
    plan: List[str]      # The execution tasks generated by the Planner Agent
    context: List[str]   # Text chunks retrieved from ChromaDB
    response: str        # The final answer formulated by the Reasoning Agent
    isValidated: bool    # Compliance pass/fail marker assigned by the Validator Agent
    retry_count: int     # Tracks the number of times we've looped back for additional retrievals


# Initialize background model connections
vector_service = VectorStoreService()

# Establish Google Gemini-2.5-Flash-Lite as our primary reasoning network
llm = ChatGoogleGenerativeAI(
    model="gemini-2.5-flash-lite",
    google_api_key=settings.GOOGLE_API_KEY,
    temperature=0.0                 # Enforce deterministic outputs for compliance tasks
)

# Bind the Pydantic structured layout schema directly to the model's token processing layer
structured_llm = llm.with_structured_output(JointResponseSchema)

# --------------------------------------------------------------------
# 🚀 MULTI-AGENT EXECUTION NODES (THE AGENTS)
# --------------------------------------------------------------------
# Route incoming queries immediately based on simple keyword checks to casual response or the full planner workflow


def entry_router(state: AgentState) -> str:
    """FRONT-GATE SHORT-CIRCUIT: Handles greetings instantly at $0.00 cost and 0 LLM calls."""
    clean_query = state["query"].strip().lower()
    greetings = ["hi", "hello", "hey", "good morning",
                 "good afternoon", "status check"]

    if any(greet == clean_query for greet in greetings):
        return "casual_response"

    return "planner"

# The casual response node provides an immediate, cost-free response for simple greetings


def casual_response_node(state: AgentState) -> dict:
    """CASUAL NODE: Instantly returns system communication without running LLM handshakes."""
    return {
        "response": "Hello! I am your Enterprise RAG Agent. Please ask an operational question.",
        "isValidated": True
    }

# The planner node generates a refined retrieval plan based on the user's query, with smart retry logic to force different search angles


def planner_node(state: AgentState) -> dict:
    """PLANNER AGENT: Analyzes user intent and develops an extraction plan."""
    current_retries = state.get("retry_count", 0)
    if current_retries > 0:
        prompt = f"Previous lookup failed. Generate an alternative set of search keywords for: '{state['query']}'"
    else:
        prompt = f"Develop a targeted retrieval query to resolve this enterprise request: '{state['query']}'"

    res = llm.invoke([
        SystemMessage(
            content="You are an expert AI operation planner. Output only the refined retrieval objective."),
        HumanMessage(content=prompt)
    ])
    return {"plan": [res.content]}

# The retriever node executes the Planner's retrieval plan against ChromaDB, returning relevant context documents for reasoning and validation


def retriever_node(state: AgentState) -> dict:
    """RETRIEVER AGENT: Executes the Planner's retrieval plan against ChromaDB."""
    refined_query = state["plan"][0] if state["plan"] else state["query"]
    retrieved_docs = vector_service.similarity_search(refined_query, k=3)
    return {"context": retrieved_docs}

# The joint reasoning and validation node forces Gemini to step through reasoning and audit checking sequentially in 1 single flight, using the structured output schema o self-audit


def joint_reasoning_and_validation_node(state: AgentState) -> dict:
    """
    MERGED NODE: Combined Reasoning and Validation Station.
    Forces Gemini to step through reasoning and audit checking sequentially in 1 single flight.
    """
    context_str = "\n---\n".join(state["context"])
    prompt = (
        f"Context Documents:\n{context_str}\n\n"
        f"User Query: {state['query']}\n\n"
        f"Formulate a direct, objective, and ultra-short response based strictly on the provided documents. "
        f"Do not write conversational filler or full paragraphs. Answer in 1 to 3 sentences maximum. "
        f"Set 'is_valid' to True if your answer is 100% supported by the context documents. "
        f"Set 'is_valid' to False if the documents are completely missing the answer or require assumptions."
    )
    try:
        structured_output = structured_llm.invoke([
            SystemMessage(
                content="You are an unyielding operational reasoning agent and strict legal compliance auditor."),
            HumanMessage(content=prompt)
        ])

        if structured_output is None:
            return {"response": "Context Insufficient", "isValidated": False}

        response_text = structured_output.response
        valid_flag = structured_output.is_valid

    except Exception:
        # Fallback to invalid state if the underlying LLM processing fails structurally
        return {"response": "Context Insufficient", "isValidated": False}

    if not valid_flag:
        response_text = "Context Insufficient"

    return {"response": response_text, "isValidated": valid_flag}

# The state incrementer node is a safe mutation function that replaces the illegal conditional edge mutation loop, ensuring we can track retry attempts without violating graph integrity rules.


def state_incrementer_node(state: AgentState) -> dict:
    """Safe node mutation function replacing the illegal conditional edge mutation loop."""
    return {"retry_count": state.get("retry_count", 0) + 1}

# The router condition function acts as the traffic controller after the reasoning and validation


def router_condition(state: AgentState):
    """Acts as the traffic controller out of the validation loops."""
    if state["isValidated"] or state["response"] == "Context Insufficient":
        return END
    if state.get("retry_count", 0) >= 2:
        return "fallback_end_node"
    return "state_incrementer_node"

# The fallback end node provides a clear safety notice if the network fails validation after max retries


def fallback_end_node(state: AgentState) -> dict:
    """Appends a clear safety notice if the network fails validation after max retries."""
    final_alert = state["response"] + \
        "\n\n⚠️ *Notice: This response could not be fully verified against internal documents after 2 validation cycles.*"
    return {"response": final_alert}


# --------------------------------------------------------------------
# GRAPH COMPILATION AND ASSEMBLY
# --------------------------------------------------------------------
workflow = StateGraph(AgentState)

workflow.add_node("casual_response", casual_response_node)
workflow.add_node("planner", planner_node)
workflow.add_node("retriever", retriever_node)
workflow.add_node("joint_reasoning_and_validation",
                  joint_reasoning_and_validation_node)
workflow.add_node("state_incrementer_node", state_incrementer_node)
workflow.add_node("fallback_end_node", fallback_end_node)

workflow.set_conditional_entry_point(
    entry_router,
    {
        "casual_response": "casual_response",
        "planner": "planner"
    }
)

workflow.add_edge("casual_response", END)
workflow.add_edge("planner", "retriever")
workflow.add_edge("retriever", "joint_reasoning_and_validation")

workflow.add_conditional_edges(
    "joint_reasoning_and_validation",
    router_condition,
    {
        END: END,
        "state_incrementer_node": "state_incrementer_node",
        "fallback_end_node": "fallback_end_node"
    }
)
workflow.add_edge("state_incrementer_node", "planner")
workflow.add_edge("fallback_end_node", END)
agent_graph = workflow.compile()
