###########################################################
# 1.0 - AGENT GRAPH DEFINITION
# This module defines the multi-agent workflow graph that orchestrates the interactions between the Planner, Retriever
# , Reasoning, and Validator agents. Each agent is implemented as a node in the graph, with specific functions that process the shared state. The graph includes conditional routing logic to ensure that if the Validator detects any hallucinations in the Reasoning Agent's output, it loops back to the Retriever for additional context retrieval. The final compiled graph is exported for execution in the main application.
#############################################################
from typing import TypedDict, List
from langgraph.graph import StateGraph, END
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.messages import SystemMessage, HumanMessage
from app.services.vector_store import VectorStoreService
from app.core.config import settings

# 1. DEFINE THE CENTRALIZED AGENT MEMORY STATE
# This dictionary represents the shared memory passed continuously between
# our agents as they execute their specialized tasks.


class AgentState(TypedDict):
    query: str           # The raw natural language question from the user
    plan: List[str]      # The execution tasks generated by the Planner Agent
    # Text chunks retrieved from ChromaDB by the Retriever Agent
    context: List[str]
    response: str        # The final answer formulated by the Reasoning Agent
    isValidated: bool    # Compliance pass/fail marker assigned by the Validator Agent
    # <-- Add this tracking key to monitor how many times we've looped back for retries
    retry_count: int


# Initialize background model connections
vector_service = VectorStoreService()

# Establish Google Gemini-2.5-Flash-Lite as our primary reasoning network
# Temperature is set to 0.0 to enforce strict factual correctness.
llm = ChatGoogleGenerativeAI(
    model="gemini-2.5-flash-lite",
    google_api_key=settings.GOOGLE_API_KEY,
    temperature=0.0                 # Enforce deterministic outputs for compliance tasks
)

# --------------------------------------------------------------------
# 2. DEFINE THE MULTI-AGENT EXECUTION NODES (THE AGENTS)
# --------------------------------------------------------------------

# Planner Agent: Analyzes the user's query and formulates a targeted retrieval plan.


def planner_node(state: AgentState) -> dict:
    """PLANNER AGENT: Analyzes user intent and develops an extraction plan."""
    prompt = f"Develop a targeted retrieval query to resolve this enterprise request: '{state['query']}'"
    res = llm.invoke([
        SystemMessage(
            content="You are an expert AI operation planner. Output only the refined retrieval objective."),
        HumanMessage(content=prompt)
    ])
    # Initialize retry count at the start of the workflow
    return {"plan": [res.content], "retry_count": 0}

# Retriever Agent: Connects to ChromaDB to fetch matching document blocks based on the Planner's output.


def retriever_node(state: AgentState) -> dict:
    """RETRIEVER AGENT: Executes the Planner's retrieval plan against ChromaDB."""
    # Using the planner's output as the query for our vector search. In a more complex implementation, the planner could generate multiple retrieval tasks or specify different retrieval strategies. For simplicity, we will assume it generates a single refined query.
    refined_query = state["plan"][0] if state["plan"] else state["query"]
    retrieved_docs = vector_service.similarity_search(refined_query, k=3)
    return {"context": retrieved_docs}

# Reasoning Agent: Synthesizes the retrieved document chunks into a coherent answer to the user's query.


def reasoning_node(state: AgentState) -> dict:
    """REASONING AGENT: Reviews document chunks to synthesize a grounded answer."""
    context_str = "\n---\n".join(
        # Combine retrieved chunks into a single string with clear separators
        state["context"])
    prompt = (
        # Provide the original user query for reference in formulating the answer.
        f"Context Documents:\n{context_str}\n\n"
        # Instruct the agent to strictly use only the provided context to answer the query, without making any assumptions or fabrications.
        f"User Query: {state['query']}\n\n"
        f"Formulate a direct, objective, and ultra-short response based strictly on the provided documents. "
        f"Do not write conversational filler or full paragraphs. Answer in 1 to 3 sentences maximum. "
        f"If the data is completely missing or inadequate, reply exactly with: 'Context Insufficient'."
    )
    res = llm.invoke([
        SystemMessage(
            content="You are an unyielding financial and operational auditing agent. You never use filler words and keep responses under 50 words."),
        HumanMessage(content=prompt)
    ])
    return {"response": res.content}


def validator_node(state: AgentState) -> dict:
    """VALIDATOR AGENT: Audits the final answer to eliminate hallucinations."""
    # Guardrail check: if the reasoning agent already failed, pass it through
    if "Context Insufficient" in state["response"]:
        return {"isValidated": True}

    # The validator's task is to scrutinize the reasoning agent's output
    # against the retrieved context.
    # It checks for any claims in the response that are not directly supported
    # by the context documents.
    # If it finds any unsupported claims, it flags the response as invalid,
    # which will trigger a loop back to the retriever for another attempt at fetching better context.
    context_str = "\n".join(state["context"])
    prompt = (
        f"Context Sources:\n{context_str}\n\n"
        f"Draft Answer: {state['response']}\n\n"
        f"Does the Draft Answer contain any assumptions not directly found in the Context Sources? "
        f"Reply with exactly 'VALID' if it is perfect, or 'INVALID' if there are unsupported claims."
    )
    res = llm.invoke([
        SystemMessage(
            content="You are a strict, objective corporate legal compliance auditor."),
        HumanMessage(content=prompt)
    ])
    return {"isValidated": "VALID" in res.content.upper()}

# --------------------------------------------------------------------
# 3. ORCHESTRATE THE CONDITIONAL AGENT ROUTING
# --------------------------------------------------------------------


def router_condition(state: AgentState):
    """
    Acts as the traffic controller. If the validator approves the answer, 
    the process ends. If it finds a hallucination, it loops back to the 
    Retriever to search for better documentation.
    """
    # If the response is valid, stop immediately
    if state["isValidated"]:
        return END

    # Safely fetch the current retry count (default to 0 if missing)
    current_retries = state.get("retry_count", 0)

    # ENFORCE THE LIMIT: If we have already retried 3 times, break the loop
    if current_retries >= 3:
        return "fallback_end_node"

    return "retriever"


def fallback_end_node(state: AgentState) -> dict:
    """Appends a clear safety notice if the network fails validation after max retries."""
    final_alert = state["response"] + \
        "\n\n⚠️ *Notice: This response could not be fully verified against internal documents after 3 validation cycles.*"
    return {"response": final_alert}


# Assemble the structural Graph workflow pipeline
workflow = StateGraph(AgentState)

# Register our agents as nodes in the graph
# Initial node that generates the retrieval plan
workflow.add_node("planner", planner_node)
# Fetches relevant document chunks based on the planner's output
workflow.add_node("retriever", retriever_node)
# Synthesizes the retrieved context into a final answer
workflow.add_node("reasoning", reasoning_node)
# Audits the reasoning output for any unsupported claims or hallucinations
workflow.add_node("validator", validator_node)
# Fallback node to handle cases where the maximum number of retries has been reached without validation success
workflow.add_node("fallback_end_node", fallback_end_node)
# Set up the sequential execution routes
# Start the workflow with the Planner Agent
workflow.set_entry_point("planner")
# After planning, move to retrieval
workflow.add_edge("planner", "retriever")
# Once we have context, move to reasoning
workflow.add_edge("retriever", "reasoning")
# After reasoning, validate the answer
workflow.add_edge("reasoning", "validator")

# Inject the smart guardrail loop conditional edge
# If validation fails, loop back to the retriever for another attempt at fetching better context
workflow.add_conditional_edges(
    "validator",
    router_condition,
    {
        END: END,
        "retriever": "retriever",
        "fallback_end_node": "fallback_end_node"
    }
)

# Connect the fallback end node to the final stop
workflow.add_edge("fallback_end_node", END)

# Compile the compiled agent graph ready for execution
# Export the graph for use in the main application
agent_graph = workflow.compile()
